# Generated by Django 3.1.5 on 2021-02-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='date',
            field=models.DateField(),
        ),
    ]
