# Generated by Django 3.1.5 on 2021-02-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0002_auto_20210201_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('flag', models.CharField(max_length=100)),
                ('eez_crossing', models.CharField(max_length=100)),
                ('violation', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Ship',
        ),
    ]
