# Generated by Django 3.1.6 on 2021-02-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0003_auto_20210201_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_id', models.IntegerField()),
                ('mmsi', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
    ]
