# Generated by Django 3.1.6 on 2021-02-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0005_filesadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesadmin',
            name='upload',
            field=models.FileField(blank=True, max_length=150, upload_to='media'),
        ),
    ]
